[build]
  # Base directory is not needed since your project is at the root
  publish = "dist/sachin-portfolio"
  command = "ng build --configuration production"

[[redirects]]
  # Redirect all paths to index.html for SPA support
  from = "/*"
  to = "/index.html"
  status = 200
